package com.sicmsb.bean;

// Generated Dec 3, 2014 1:40:43 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SicmsbTb generated by hbm2java
 */
@Entity
@Table(name = "sicmsb_tb", catalog = "sicmsb")
public class SicmsbTb implements java.io.Serializable {

	private Integer id;
	private String name;
	private String email;
	private String phone;
	private String department;
	private String hometown;

	public SicmsbTb() {
	}

	public SicmsbTb(String name, String email, String phone, String department,
			String hometown) {
		this.name = name;
		this.email = email;
		this.phone = phone;
		this.department = department;
		this.hometown = hometown;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone", length = 45)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "department", length = 45)
	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@Column(name = "hometown", length = 45)
	public String getHometown() {
		return this.hometown;
	}

	public void setHometown(String hometown) {
		this.hometown = hometown;
	}

}
